### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Shelf-Desktop#16]
Attempt to save https://www.youtube.com/channel/UC8HFOUdnMnpoWmQMgeKoB3A link resulted in the error:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("yt3.ggpht.com")), port: None, path: "/CajG8KRONNS9zrU0sUb7W3JApVYtYux3dGsV0uSJ8tlbweeCXaNClzZu7KLcLiEa7J-9DV9K=s900-c-k-c0x00ffffff-no-rj", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', core/src/base/link.rs:155:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://user-images.githubusercontent.com/581023/185669027-71cd5a2b-f443-4198-b72e-d01d7ba4d588.mp4

**Comment by kirillt** [comment]
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("yt3.ggpht.com")), port: None, path: "/CajG8KRONNS9zrU0sUb7W3JApVYtYux3dGsV0uSJ8tlbweeCXaNClzZu7KLcLiEa7J-9DV9K=s900-c-k-c0x00ffffff-no-rj", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', core/src/base/link.rs:155:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: tokio::runtime::task::core::CoreStage<T>::poll
   8: tokio::runtime::task::harness::poll_future
   9: tokio::runtime::task::harness::Harness<T,S>::poll
  10: std::thread::local::LocalKey<T>::with
  11: tokio::runtime::thread_pool::worker::Context::run_task
  12: tokio::runtime::thread_pool::worker::Context::run
  13: tokio::macros::scoped_tls::ScopedKey<T>::set
  14: tokio::runtime::thread_pool::worker::run
  15: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  16: tokio::runtime::task::harness::Harness<T,S>::poll
  17: tokio::runtime::blocking::pool::Inner::run
```

**Comment by mberry** [comment]
This perhaps could be related to youtube blocking certain useragent?

Trying the same link I got it working with a preview:

![image](https://github.com/ARK-Builders/ARK-Shelf-Desktop/assets/17392435/87088ec5-e17f-4b63-8b00-a0e5e680779f)

**Comment by kirillt** [comment]
@mberry maybe.. I think just handling errors in similar cases would be enough for the start.

**Comment by gwendalF** [comment]
@kirillt  I don't have the error either. Can you check my commit b3be058e82c7b5962f92eaf0af5036acb0810ab3 to validate if this error is handled or not?
Thanks
